# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hymvb08HLmyKg3Z41yX-Jf_S2gnlzht7
"""

!pip install transformers datasets accelerate pyarrow==19.0.0

# Import the necessary modules
from google.colab import userdata
import os

# --- CORRECTED CODE STARTS HERE ---

# 1. We check if the secret 'HF_TOKEN' exists and retrieve its value.
#    We use 'HF_TOKEN' as this is the standard name the Hugging Face library looks for.
hf_token_value = userdata.get('huggingface')

if hf_token_value is not None:
    # 2. If the token is found, set it as an environment variable.
    os.environ['huggingface'] = hf_token_value
    print("Hugging Face token loaded securely from Colab Secrets.")
else:
    # 3. If it's not found, prompt the user or issue a warning.
    print("WARNING: HF_TOKEN not found in Colab Secrets. Please configure it in the left sidebar.")

# --- CORRECTED CODE ENDS HERE ---

csv_data = """
text,label
Do you know any free online courses for coding that I can access from Kenya?,FIND_FREE_COURSE
I'm broke but I want to study web development; any zero-cost classes?,FIND_FREE_COURSE
Point me to free tutorials for Excel that don’t require a credit card.,FIND_FREE_COURSE
Are there open courses I can join for free to improve my English writing?,FIND_FREE_COURSE
I need a no-charge course on project management; any suggestions?,FIND_FREE_COURSE
Can I get a scholarship or fully free course for learning Python?,FIND_FREE_COURSE
Any MOOC offering free certificates in digital marketing for African students?,FIND_FREE_COURSE
Show me websites where I can study cloud computing at zero cost.,FIND_FREE_COURSE
I have no budget; how can I learn graphic design for free?,FIND_FREE_COURSE
Recommend free ICT courses that work on a low-bandwidth connection.,FIND_FREE_COURSE
Are there free video lessons on entrepreneurship for youths in Nigeria?,FIND_FREE_COURSE
I’m looking for a free online class about renewable energy basics.,FIND_FREE_COURSE
Where can I find cost-free training on financial literacy?,FIND_FREE_COURSE
Suggest a free cyber security course that doesn’t charge for materials.,FIND_FREE_COURSE
Please list free platforms to learn mobile app development.,FIND_FREE_COURSE
What are the best resources to start learning machine learning for future jobs?,SEEK_AI_SKILLS
I want to get into AI; which courses should I follow?,SEEK_AI_SKILLS
Guide me to AI skill programs that employers look for.,SEEK_AI_SKILLS
How can I upskill in deep learning quickly?,SEEK_AI_SKILLS
Show me online classes to master data analysis with AI tools.,SEEK_AI_SKILLS
I need AI skills to automate farm tasks; any course suggestions?,SEEK_AI_SKILLS
Recommend AI training focused on natural language processing.,SEEK_AI_SKILLS
Point me to affordable AI bootcamps for African youth.,SEEK_AI_SKILLS
Where can I learn about computer vision to build smart cameras?,SEEK_AI_SKILLS
I’m interested in reinforcement learning; which beginner-friendly course is good?,SEEK_AI_SKILLS
Help me find an AI course that teaches TensorFlow.,SEEK_AI_SKILLS
Which programme can equip me with AI and robotics skills?,SEEK_AI_SKILLS
What online degree gives strong AI foundations?,SEEK_AI_SKILLS
Suggest a pathway to become an AI engineer.,SEEK_AI_SKILLS
I want to understand ethical AI; any training recommendations?,SEEK_AI_SKILLS
I’m totally new to programming; where do I start?,ASK_BEGINNER_INFO
What is the simplest explanation of cloud computing?,ASK_BEGINNER_INFO
Can you break down how the internet works for a beginner?,ASK_BEGINNER_INFO
I don’t understand algorithms; explain like I’m in secondary school.,ASK_BEGINNER_INFO
How do I begin learning Excel from scratch?,ASK_BEGINNER_INFO
What basics do I need before studying data science?,ASK_BEGINNER_INFO
I heard about blockchain; what does it actually mean?,ASK_BEGINNER_INFO
Give me a beginner guide to digital marketing.,ASK_BEGINNER_INFO
Explain Python variables in simple terms.,ASK_BEGINNER_INFO
I’m confused by HTML tags; can you simplify?,ASK_BEGINNER_INFO
What starter resources exist for networking fundamentals?,ASK_BEGINNER_INFO
Where should a complete newbie learn about databases?,ASK_BEGINNER_INFO
Could you explain machine learning without heavy maths?,ASK_BEGINNER_INFO
I know nothing about coding; is there a step-by-step course?,ASK_BEGINNER_INFO
What’s the easiest way to understand APIs?,ASK_BEGINNER_INFO
Which online course will give me a recognized certificate in project management?,CERT_PATH_REQUEST
I need a Google certified program for data analytics—where can I enroll?,CERT_PATH_REQUEST
Point me to a course that offers a Coursera certificate in cybersecurity.,CERT_PATH_REQUEST
How do I earn an AWS certification from Kenya?,CERT_PATH_REQUEST
Suggest a pathway to get a Microsoft Excel specialist certificate.,CERT_PATH_REQUEST
I’m looking for a diploma-level online course with accreditation in digital marketing.,CERT_PATH_REQUEST
Any training that provides a blockchain certificate employers respect?,CERT_PATH_REQUEST
Show me a programme granting Cisco CCNA certification online.,CERT_PATH_REQUEST
I want an accredited certificate in graphic design; any options?,CERT_PATH_REQUEST
Recommend courses that include a verified certificate in Python.,CERT_PATH_REQUEST
Where can I get a free but official certificate in customer service?,CERT_PATH_REQUEST
I need a recognized certificate for teaching English online.,CERT_PATH_REQUEST
Help me find an online AI course that awards a professional credential?,CERT_PATH_REQUEST
How can I get certified in Scrum while studying remotely?,CERT_PATH_REQUEST
Which MOOCs issue certificates that are accepted by employers in Nigeria?,CERT_PATH_REQUEST
Hi there!,GENERAL_GREETING
"Hello, chatbot.",GENERAL_GREETING
"Good morning, how are you?",GENERAL_GREETING
"Hey, what’s up?",GENERAL_GREETING
"Hi, I need some help.",GENERAL_GREETING
"Hello from Lagos!",GENERAL_GREETING
"Good afternoon.",GENERAL_GREETING
"Hey mentor!",GENERAL_GREETING
"Hi buddy, can we chat?",GENERAL_GREETING
"Hello there 😊",GENERAL_GREETING
"Good evening, assistant.",GENERAL_GREETING
"Howdy!",GENERAL_GREETING
"Yo!",GENERAL_GREETING
"Greetings!",GENERAL_GREETING
"Hi AI friend!",GENERAL_GREETING
"""

# This cell is now empty as its content has been moved to Omz0vMt-IKEo for better robustness.

# This cell is now empty as its content has been moved to Omz0vMt-IKEo for better robustness.

import pandas as pd
from io import StringIO
from datasets import Dataset, ClassLabel
from transformers import AutoTokenizer

# Define label_list (moved from xyv9nr2MBfFZ)
label_list = [
    "FIND_FREE_COURSE",
    "SEEK_AI_SKILLS",
    "ASK_BEGINNER_INFO",
    "CERT_PATH_REQUEST",
    "GENERAL_GREETING"
]

# Create DataFrame and Dataset (moved from xyv9nr2MBfFZ)
df = pd.read_csv(StringIO(csv_data))
dataset = Dataset.from_pandas(df)
dataset = dataset.cast_column("label", ClassLabel(names=label_list))
print("Dataset created:", dataset)

# Load tokenizer (moved from QvR2nh9wEGSb)
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
print("Tokenizer loaded for model:", model_name)

def tokenize_function(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128,
    )

tokenized_ds = dataset.map(tokenize_function, batched=True)

print("Tokenized Dataset created:", tokenized_ds)

from huggingface_hub import notebook_login
notebook_login()

#This will guide you through authenticating with your Hugging Face account so that the `Trainer` can correctly push the model to your namespace, `"johnjeavons"`. Let me know once you've successfully logged in!

import os
# CRITICAL FIX: Explicitly disable Weights & Biases logging to prevent the 'Abort' error
# caused by the interactive API key prompt timing out.
os.environ["WANDB_DISABLED"] = "true"

from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

# --- Required variables (replace placeholders) ---
# NOTE: These variables are expected to be defined earlier in your notebook
model_name = "distilbert-base-uncased" # Example: Replace with your actual model name
# FIX for IndexError: The dataset has 5 unique labels (0, 1, 2, 3, 4), so the list must have 5 entries.
# I've added "skill_E" to match the 5 classes found in your data.
label_list = ["skill_A", "skill_B", "skill_C", "skill_D", "skill_E"]

# FIX FOR 403 ERROR: You MUST replace this placeholder with your actual Hugging Face username!
hf_username = "johnjeavons"

# Ensure the tokenized_ds variable holds your processed dataset
# This is usually the output of dataset.map(tokenize_function, batched=True)
# If your dataset is not named 'tokenized_ds', adjust the Trainer initialization below.
# For this example, we assume 'tokenized_ds' is defined.
# tokenized_ds = ... (Your preprocessed dataset goes here)
# ----------------------------------------------------


# --- Dataset preparation (moved from previous cell to ensure availability) ---
tokenized_ds = tokenized_ds.rename_column("label", "labels")
tokenized_ds.set_format("torch")

# Split the dataset into training and evaluation sets
splits = tokenized_ds.train_test_split(test_size=0.2, seed=42)
train_dataset = splits["train"]
eval_dataset = splits["test"]

print(f"Training dataset size: {len(train_dataset)}")
print(f"Evaluation dataset size: {len(eval_dataset)}")
# -----------------------------------------------------------------------------


# 1. Load the model with new classification head
# The number of labels is now 5, matching the data (0-4).
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(label_list),
)
print("Model loaded successfully. New classification head initialized.")

# 2. Define repository name
repo_name   = f"{hf_username}/sdg4-skill-navigator"

# 3. Define Training Arguments
training_args = TrainingArguments(
    output_dir="sdg4-skill-navigator", # Local output folder for checkpoints
    hub_model_id=repo_name,           # Repository name on Hugging Face Hub
    push_to_hub=True,                 # Automatically push model to the Hub
    num_train_epochs=10,              # Increased number of epochs to 10
    per_device_train_batch_size=16,   # Increased batch size to 16
    learning_rate=2e-5,               # Initial learning rate
    weight_decay=0.01,                # L2 regularization
    logging_steps=10,                 # Log training metrics every 10 steps
    report_to='none',                 # Disables Weights & Biases (secondary safeguard)
    # Removed evaluation_strategy as it's causing TypeError
    save_strategy="epoch",            # Save model at the end of each epoch
    # Removed load_best_model_at_end and metric_for_best_model as they depend on evaluation_strategy
)
print("TrainingArguments defined successfully.")

# 4. Instantiate the Trainer
# NOTE: The Trainer expects a variable named 'tokenized_ds' to exist in your environment.
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,      # Use the new train_dataset
    eval_dataset=eval_dataset,        # Use the new eval_dataset
    # Optional: If you want metrics, add: compute_metrics=compute_metrics_function,
)
print("Trainer instantiated. Starting training...")

# 5. Start training!
trainer.train()

print(f"\nTraining complete. Model pushed to: https://huggingface.co/{repo_name}")

from transformers import pipeline

# --- Configuration matching your trained model ---
MODEL_PATH = "johnjeavons/sdg4-skill-navigator"

# These labels must exactly match the list you used during training
# label_list = ["skill_A", "skill_B", "skill_C", "skill_D", "skill_E"]
# Note: The pipeline automatically maps these, but listing them helps verification.

# Sample text to test the classifier
sample_text = "I have extensive experience in curriculum design, developing engaging lesson plans, and assessing student performance using formative and summative methods."

print(f"Loading classifier pipeline from: {MODEL_PATH}")

# 1. Load the model using the text-classification pipeline
# This automatically handles tokenization, model forward pass, and softmax/label mapping.
try:
    # Pass the tokenizer object directly to the pipeline
    classifier = pipeline("text-classification", model=MODEL_PATH, tokenizer=tokenizer)
    print("Pipeline loaded successfully.")

    # 2. Run inference
    results = classifier(sample_text)

    # 3. Display results
    print("-" * 50)
    print(f"Input Text: '{sample_text}'")
    print("-" * 50)

    # The result is a list of dictionaries (one prediction per class for single-label, or top labels)
    if results:
        # Assuming single-label classification, we look at the top result
        top_result = results[0]
        print(f"Prediction: {top_result['label']}")
        print(f"Confidence: {top_result['score']:.4f}")
        print("-" * 50)
    else:
        print("Inference returned no results.")

except Exception as e:
    print(f"An error occurred during inference. Ensure you are logged in if the model is private, or check the model path.")
    print(f"Error details: {e}")

from transformers import pipeline

# --- Configuration matching your trained model ---
MODEL_PATH = "johnjeavons/sdg4-skill-navigator"
TOKENIZER_PATH = "distilbert-base-uncased"

# Map the generic numerical labels back to your human-readable skill categories.
# This list MUST match the order and content of your label_list from training.
LABEL_MAP = {
    'LABEL_0': 'skill_A (Foundational Skills)',
    'LABEL_1': 'skill_B (Core Job Skills)',
    'LABEL_2': 'skill_C (Digital Literacy)',
    'LABEL_3': 'skill_D (Pedagogical Skills / Training)',
    'LABEL_4': 'skill_E (Sustainable Development & Citizenship)'
}

# Sample text to test the classifier (Currently leaning towards Pedagogical Skills)
sample_text = "I have extensive experience in curriculum design, developing engaging lesson plans, and assessing student performance using formative and summative methods."

print(f"Loading classifier pipeline from model: {MODEL_PATH}")

# 1. Load the model using the text-classification pipeline
try:
    classifier = pipeline(
        "text-classification",
        model=MODEL_PATH,
        tokenizer=TOKENIZER_PATH
    )

    print("Pipeline loaded successfully.")

    # 2. Run inference
    results = classifier(sample_text)

    # 3. Display results
    print("-" * 50)
    print(f"Input Text: '{sample_text}'")
    print("-" * 50)

    if results:
        top_result = results[0]
        predicted_label_key = top_result['label']

        # Get the human-readable label from the map
        human_readable_label = LABEL_MAP.get(predicted_label_key, predicted_label_key)

        print(f"Prediction: {human_readable_label}")
        print(f"Confidence: {top_result['score']:.4f}")
        print("-" * 50)
    else:
        print("Inference returned no results.")

except Exception as e:
    print(f"An error occurred during inference. Please check your model name and network connection.")
    print(f"Error details: {e}")

from transformers import pipeline

clf = pipeline(
    "text-classification",
    model=MODEL_PATH,
    tokenizer=TOKENIZER_PATH,
)

test_sentence = "Can you suggest a totally free Python course?"
print(clf(test_sentence))